version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the linter binary
    cmds:
      - go build -o bin/newline-after-block ./cmd/newline-after-block

  install:
    desc: Install the linter binary to $GOPATH/bin
    cmds:
      - go install ./cmd/newline-after-block

  test:
    desc: Run all tests
    cmds:
      - go test -cover ./...

  test-verbose:
    desc: Run all tests with verbose output
    cmds:
      - go test -v -cover ./...

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  lint-fix:
    desc: Run golangci-lint with auto-fix
    cmds:
      - golangci-lint run --fix

  run:
    desc: Run the linter on the project itself
    cmds:
      - go run ./cmd/newline-after-block ./...

  clean:
    desc: Clean build artifacts and generated files
    cmds:
      - rm -rf bin/
      - rm -f coverage.out coverage.html

  mod-tidy:
    desc: Tidy Go module dependencies
    cmds:
      - go mod tidy

  verify:
    desc: Run all verification tasks (build, test, lint)
    cmds:
      - task: mod-tidy
      - task: build
      - task: test
      - task: lint
